var body = document.querySelector('body');
var bodyClass = body.classList;
var checks = document.querySelector('#checkbox');
var footer = document.querySelector('.footer');
var light = document.querySelector('.light');
var dark = document.querySelector('.dark');
var flex_top = document.querySelector('.flex_top');
var tp2 = document.querySelector('.tp2');
var tp3 = document.querySelector('.tp3');
var tp4 = document.querySelector('.tp4');
var vflex1 = document.querySelector('.vflex1');
var vflex2 = document.querySelector('.vflex2');
var vflex3 = document.querySelector('.vflex3');
var vflex4 = document.querySelector('.vflex4');
var vflex5 = document.querySelector('.vflex5');
var vflex6 = document.querySelector('.vflex6');
var vflex7 = document.querySelector('.vflex7');
var vflex8 = document.querySelector('.vflex8');

checks.addEventListener('click', () => {
    body.classList.toggle("light");
    body.classList.toggle("dark");
    checks.classList.toggle("btn-light");
    checks.classList.toggle("btn-dark");
    footer.classList.toggle("footer-light");
    footer.classList.toggle("footer-dark");
    flex_top.classList.toggle("flex-light");
    flex_top.classList.toggle("flex-dark");
    tp2.classList.toggle("flex-light");
    tp2.classList.toggle("flex-dark");
    tp3.classList.toggle("flex-light");
    tp3.classList.toggle("flex-dark");
    tp4.classList.toggle("flex-light");
    tp4.classList.toggle("flex-dark");
    vflex1.classList.toggle("flex-light");
    vflex1.classList.toggle("flex-dark");
    vflex2.classList.toggle("flex-light");
    vflex2.classList.toggle("flex-dark");
    vflex3.classList.toggle("flex-light");
    vflex3.classList.toggle("flex-dark");
    vflex4.classList.toggle("flex-light");
    vflex4.classList.toggle("flex-dark");
    vflex5.classList.toggle("flex-light");
    vflex5.classList.toggle("flex-dark");
    vflex6.classList.toggle("flex-light");
    vflex6.classList.toggle("flex-dark");
    vflex7.classList.toggle("flex-light");
    vflex7.classList.toggle("flex-dark");
    vflex8.classList.toggle("flex-light");
    vflex8.classList.toggle("flex-dark");
});